# Generated by Django 5.2.5 on 2025-08-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='media_type',
            field=models.CharField(max_length=25),
        ),
    ]
